name: swervpay_widget
description: Official Swervpay Widget for Flutter https://docs.swervpay.co/sdks/widget.
version: 0.0.3
homepage: https://docs.swervpay.co/sdks/flutter
repository: https://github.com/swerv-ltd/swervpay_flutter
issue_tracker: https://github.com/swerv-ltd/swervpay_flutter/issues
documentation: https://docs.swervpay.co/sdks/flutter

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
